# This is a basic workflow to help you get started with Actions

name: Deploy to Staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - develop


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    #Check that PHPUnit Passes
    name: Laravel PHPUnit
    steps:
    - uses: actions/checkout@v1

    #Authenticate Nova
    - name: Install dependencies
      run: composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"

    #Run PHPUnit
    - uses: nathanheffley/laravel-phpunit-action@master
  vapor:
    runs-on: ubuntu-latest
    name: Vapor Deploy to Staging
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    #Authenticate Nova
    - name: Install dependencies
      run: composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"

    #Deploy to Vapor
    - name: Deploy to Vapor Staging
      env:
        VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
      uses: ubient/laravel-vapor-action@1.1.0
      with:
        args: deploy staging --commit="${{ github.sha }}"